/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author bauti
 */

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class Diagnosis extends javax.swing.JFrame {

    /**
     * Creates new form Diagnosis
     */
    private JTextField diagnosisId;
    private JComboBox<String> conditioncombobox;
    private JButton saveButton; 
    
    public Diagnosis() {
        initComponents();
        
        setTitle("Diagnosis");
        setSize(400, 300);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLayout(null);

        JLabel diagnosisIdLabel = new JLabel("Diagnosis Id:");
        diagnosisIdLabel.setBounds(50, 50, 100, 25);
        add(diagnosisIdLabel);

        diagnosisId = new JTextField();
        diagnosisId.setBounds(150, 50, 200, 25);
        add(diagnosisId);

        JLabel conditionLabel = new JLabel("Eye Condition:");
        conditionLabel.setBounds(50, 100, 100, 25);
        add(conditionLabel);

        String[] conditions = {"Myopia", "Hyperopia", "Astigmatism", "Presbyopia", "Glaucoma"};
        conditioncombobox = new JComboBox<>(conditions);
        conditioncombobox.setBounds(150, 100, 200, 25);
        add(conditioncombobox);

        saveButton = new JButton("Save");
        saveButton.setBounds(150, 150, 100, 30);
        add(saveButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        refractivecombobox = new javax.swing.JComboBox<>();
        save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);

        jLabel1.setFont(new java.awt.Font("Oswald", 1, 24)); // NOI18N
        jLabel1.setText("Diagnosis");

        jLabel2.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        jLabel2.setText("Diagnosis Id:");

        jLabel3.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        jLabel3.setText("Eye Condition: ");

        refractivecombobox.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        refractivecombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Myopia", "Hyperopia", "Astigmatism", "Presbyopia", "Glaucoma" }));
        refractivecombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refractivecomboboxActionPerformed(evt);
            }
        });

        save.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(refractivecombobox, 0, 1, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                .addGap(107, 107, 107))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(save)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refractivecombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(34, 34, 34)
                .addComponent(save)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void refractivecomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refractivecomboboxActionPerformed
        // Get the selected refractive error from the combo box
    String selectedCondition = (String) conditioncombobox.getSelectedItem();
    
    // Check the selected refractive error
    if (selectedCondition != null) {
        switch (selectedCondition.toLowerCase()) {
            case "myopia":
                // Logic for Myopia
                System.out.println("Myopia(nearsightedness)");
                break;

            case "hyperopia":
                // Logic for Hyperopia
                System.out.println("Hyperopia (farsightedness).");
                break;

            case "astigmatism":
                // Logic for Astigmatism
                System.out.println("Astigmatism (blurred vision).");
                break;

            case "presbyopia":
                // Logic for Presbyopia
                System.out.println("Presbyopia (age-related difficulty seeing close objects).");
                break;
                
            case "glaucoma":
                
                System.out.println("Glaucoma.");
                break;

            default:
                // Handle any unexpected values
                System.out.println("Invalid selection: " + selectedCondition);
                break;
        }
    } else {
        System.out.println("No refractive error selected.");
    }
    }//GEN-LAST:event_refractivecomboboxActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        
        String diagnosisID = diagnosisId.getText(); // Diagnosis ID
    String condition = (String) conditioncombobox.getSelectedItem(); // Selected Condition

    // Validation kung walang laman ang Diagnosis ID
    if (diagnosisID.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a Diagnosis ID.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Ipakita ang ViewPrescription UI at ipasa ang data
    ViewPrescription viewPrescription = new ViewPrescription(diagnosisId, condition);
    viewPrescription.setVisible(true);

    // Isara ang kasalukuyang UI (Diagnosis UI)
    this.dispose();        
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diagnosis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diagnosis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diagnosis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diagnosis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        new Diagnosis();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diagnosis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> refractivecombobox;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
